using BjeekFinance.Domain.Enums;

namespace BjeekFinance.Domain.Entities;

/// <summary>
/// UC-FIN-CASH-01: Cash ride/order settlement record.
/// Tracks expected vs reported cash per driver per settlement period,
/// variance computation, and auto-adjustment vs manual review routing.
/// </summary>
public class CashSettlement : BaseEntity
{
    public Guid DriverId { get; set; }
    public Guid WalletId { get; set; }

    /// <summary>System-computed expected cash total from completed cash trips.</summary>
    public decimal ExpectedCashTotal { get; set; }

    /// <summary>Driver-reported cash total at settlement time.</summary>
    public decimal ReportedCashTotal { get; set; }

    /// <summary>ReportedCashTotal − ExpectedCashTotal (negative = shortfall).</summary>
    public decimal VarianceAmount { get; set; }

    public decimal CommissionReceivableAmount { get; set; }

    public CashSettlementStatus Status { get; set; } = CashSettlementStatus.Pending;

    /// <summary>|Variance| > SAR 3 → true, requires Finance Admin review.</summary>
    public bool VarianceFlag { get; set; }

    /// <summary>JSON array of trip IDs included in this settlement.</summary>
    public string? TripIdsJson { get; set; }

    public string? Notes { get; set; }
    public Guid? ReviewedByActorId { get; set; }
    public DateTime? ReviewedAt { get; set; }
    public Guid? AuditLogEntryId { get; set; }
    public DateTime? CompletedAt { get; set; }

    // ── UC-AD-FIN-03: City / zone filter ─────────────────────────────────────
    public Guid? CityId { get; set; }

    // ── UC-AD-FIN-03: Fraud escalation (UC-AD-FIN-05 placeholder) ────────────
    public DateTime? EscalatedToFraudAt { get; set; }
    public string? FraudCaseId { get; set; }

    // ── UC-AD-FIN-03: Ledger reconciliation check ───────────────────────────
    /// <summary>Ledger total for the same trips during reconciliation period. Must match ExpectedCashTotal.</summary>
    public decimal? LedgerTotal { get; set; }
    public bool LedgerMatch { get; set; } = true;

    // ── Navigation ─────────────────────────────────────────────────────────────
    public Wallet Wallet { get; set; } = null!;
}

/// <summary>
/// UC-AD-FIN-04: ZATCA-compliant VAT report.
/// Immutable after generation. Stores CSV content for direct download.
/// Tracks platform rides, orders, Instant Pay fee VAT, and merchant-specific VAT.
/// </summary>
public class VatReport : BaseEntity
{
    public DateTime PeriodStart { get; set; }
    public DateTime PeriodEnd { get; set; }
    public Guid? MerchantActorId { get; set; }
    public string? ServiceType { get; set; }

    public decimal TotalGross { get; set; }
    public decimal TotalVat { get; set; }
    public decimal TotalNet { get; set; }

    /// <summary>Instant Pay fee VAT — platform liability, not passed to driver.</summary>
    public decimal InstantPayFeeVat { get; set; }

    /// <summary>Number of lines with VAT = 0 but Gross > 0 (missing tax config).</summary>
    public int FlaggedMissingConfigCount { get; set; }

    /// <summary>JSON blob: full line items for the report.</summary>
    public string ReportDataJson { get; set; } = string.Empty;

    /// <summary>CSV content for download.</summary>
    public string? CsvContent { get; set; }

    /// <summary>ZATCA-compliant export format identifier.</summary>
    public string ExportFormat { get; set; } = "CSV";

    public Guid GeneratedByActorId { get; set; }
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// UC-AD-FIN-03: Stored reconciliation report.
/// Generated by Finance Admin for audit trail. Immutable after creation.
/// </summary>
public class ReconciliationReport : BaseEntity
{
    public DateTime DateFrom { get; set; }
    public DateTime DateTo { get; set; }
    public Guid? CityId { get; set; }

    /// <summary>Total expected cash from ledger for the period.</summary>
    public decimal TotalExpectedCash { get; set; }

    /// <summary>Total reported cash from driver settlements.</summary>
    public decimal TotalReportedCash { get; set; }

    /// <summary>Total variance across all settlements in range.</summary>
    public decimal TotalVariance { get; set; }

    /// <summary>Number of auto-adjusted settlements (≤ SAR 3 variance).</summary>
    public int AutoAdjustedCount { get; set; }

    /// <summary>Number of flagged settlements (> SAR 3).</summary>
    public int FlaggedCount { get; set; }

    /// <summary>Number of escalated to fraud.</summary>
    public int EscalatedCount { get; set; }

    /// <summary>True when ledger totals match settlement totals exactly.</summary>
    public bool LedgerReconciled { get; set; }

    /// <summary>JSON blob: full detail lines for the report.</summary>
    public string ReportDataJson { get; set; } = string.Empty;

    /// <summary>Admin who generated this report.</summary>
    public Guid GeneratedByActorId { get; set; }

    /// <summary>CSV content stored for download.</summary>
    public string? CsvContent { get; set; }

    /// <summary>Timestamp when report was generated.</summary>
    public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;
}
