// <auto-generated />
using BjeekFinance.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable
#pragma warning disable CS1591

namespace BjeekFinance.Infrastructure.Data.Migrations;

[DbContext(typeof(BjeekFinanceDbContext))]
partial class BjeekFinanceDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("BjeekFinance.Domain.Entities.Wallet", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<string>("ActorType").HasMaxLength(20).IsRequired();
            b.Property<Guid>("ActorId").IsRequired();
            b.Property<string>("Currency").HasMaxLength(3).HasDefaultValue("SAR");
            b.Property<decimal>("BalanceAvailable").HasPrecision(12, 2).HasDefaultValue(0m);
            b.Property<decimal>("BalancePending").HasPrecision(12, 2).HasDefaultValue(0m);
            b.Property<decimal>("BalanceHold").HasPrecision(12, 2).HasDefaultValue(0m);
            b.Property<decimal>("CashReceivable").HasPrecision(12, 2).HasDefaultValue(0m);
            b.Property<decimal>("BalanceRefundCredit").HasPrecision(12, 2).HasDefaultValue(0m);
            b.Property<decimal>("BalancePromoCredit").HasPrecision(12, 2).HasDefaultValue(0m);
            b.Property<decimal>("BalanceCourtesyCredit").HasPrecision(12, 2).HasDefaultValue(0m);
            b.Property<string>("KycStatus").HasMaxLength(20).HasDefaultValue("Unverified");
            b.Property<string>("InstantPayTier").HasMaxLength(10).HasDefaultValue("TierA");
            b.Property<bool>("InstantPayEnabled").HasDefaultValue(true);
            b.Property<int>("InstantPayDailyCount").HasDefaultValue(0);
            b.Property<bool>("IsInDunning").HasDefaultValue(false);
            b.Property<int>("FraudScore").HasDefaultValue(0);
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex(new[] { "ActorId", "ActorType" }).IsUnique();
            b.ToTable("Wallets");
        });

        // Additional entity snapshots omitted for brevity —
        // EF Core regenerates this file via `dotnet ef migrations add`
        // The InitialCreate migration above is the authoritative schema source.
#pragma warning restore 612, 618
    }
}
